# HTTP监听端口
server:
  port: 8888
  tomcat:
    # 应用所在目录
    basedir: /home/ubuntu/alarm-bot-1.0.0-SNAPSHOT
    accesslog:
      enabled: true
      suffix: '.log'
      prefix: access
      file-date-format: '.yyyy-MM-dd'
      directory: 'logs'

# datasource config
spring:
  datasource:
    username: bot
    password: Test!@#$1234
    url: jdbc:mysql://localhost:3306/alarm-bot?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver

    # hikari数据源特性配置
    hikari:
      # 最大连接数,默认值10.
      maximum-pool-size: 100
      # 最小空闲连接，默认值10.
      minimum-idle: 5
      # 连接超时时间(毫秒),默认值30秒.
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000(10分钟),只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      #如果大于等于 max-lifetime 且 max-lifetime>0,则会被重置为0.
      idle-timeout: 600000
      #连接最大存活时间,默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 3000000
      #连接测试查询
      connection-test-query: select 1

# lark config
lark:
  app-id: cli_a28b5ee9d8fad00d
  app-secret: KmGWVPrHZT4fqtHiHRLmreps7mym6X0e
  verify-token: EwqCX3PI73oETHorzP5B4czbzTTx28ZY
  encrypt-key: Z4ic2Gi3iFDVvurIzakLnRUpKGExHyLX

alarm-bot:
  # serviceId对应的正则表达式，只允许有一对括号
  project-name-reg-exp: 'PINPOINT Alarm - (\w+-\w+)'
  reply-alarm: '告警信息已收到，已另外创建群聊沟通，解决后会同步进度到本群'
  reply-event-solved: '收到，本群预计5分钟后解散，感谢大家的参与！'
  not-in-alarm-group: '当前群不支持 /solve 指令'
  solve-summary-missing: '告警小结缺失。\n使用帮助：使用方式：@Bot   /solve   <小结信息> \n举例说明：@Bot   /solve   空指针问题，已重新发版解决'
  reply-solved-to-chat-group: '告警已解除，处理时效：%d分钟'